### ISSUE TITLE
hyphen breaking

### ISSUE THREAD

**Issue by wulfsolter** [lathonez/clone-row#8]
Either here or in Wherewolf's build.sh. Posting for posterity (and if I post it to your GH, you'll not let me forget about it)

<img width="780" alt="screen shot 2016-10-05 at 11 40 10 am" src="https://cloud.githubusercontent.com/assets/1692132/19095147/b2344c5a-8af0-11e6-94c9-5a5694b9eb47.png">

**Comment by lathonez** [comment]
@wulfsolter - it's the behaviour of `build.sh`. Historically we've used hyphens in branch names to separate apps out of a single pool:
- `offroadadventures-checkin`
- `offroadadventures-feedback`

https://github.com/WherewolfNZ/helperscripts/blob/master/build.sh#L196

Thus running for the branch `wherewolf-offroadadventures-feedback` will clone the pool `offroadadventures`, but running for the branch `wherewolf-offroad-adventures-feedback` will clone the pool `offroad`

> Explicit is better than implicit.
